language: php
php:
  - 5.4
  - 5.5
  - hhvm

branches:
  only:
    - develop

env:
  - LIB_PATH=vendor/

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar update --dev --prefer-dist
  - vendor/bin/phpunit -c phpunit.xml --bootstrap tests/helper.php tests/
  - vendor/bin/behat -f progress
  - vendor/bin/behat -f progress -p acceptance

script: bin/amaka :build
