language: php
php:
  - "5.3"
  - "5.4"

branches:
  only:
    - develop

env:
  - LIB_PATH=vendor/

before_script:
  - curl -s https://getcomposer.org/installer | php
  - php composer.phar update --dev

script: php bin/amaka Test
